### ISSUE TITLE
Not able to use Git lfs pull

### ISSUE THREAD

**Issue by geeky-programer** [impresso/llm-transcript-postcorrection#37]
Hello, 

The git lfs storage is full and I cannot access the code repo. This is exciting work. Looking forward to access. 

`[llm-transcript-postcorrection]$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                          
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

**Comment by EmanuelaBoros** [comment]
Thanks. I'm looking into it.

**Comment by EmanuelaBoros** [comment]
Hello @geeky-programer, the LFS was deactivated, you should be able to clone without it.

Best

**Comment by geeky-programer** [comment]
Thank you. Will clone again
