### ISSUE TITLE
Cannot install genalog dependancy on python 3.9

### ISSUE THREAD

**Issue by geeky-programer** [impresso/llm-transcript-postcorrection#42]
Hello, 
I cannot use requirements .txt to install packages.
I have been trying to use your repository to get results on post-correction activities. 
I am not able to install genalog package because of dependency issues with numpy and opencv-python packages.
Is there a work around to use the genalog package ?

Thank you in advance

**Comment by EmanuelaBoros** [comment]
Genalog is required. You can take a look at what their [developers](https://github.com/microsoft/genalog) are saying. 

@geeky-programer For the requirements, I only can help if you give me more details (system, Python version, errors, etc.).

**Comment by geeky-programer** [comment]
System: rocky linux 9
Python version : 3.9
I have followed the link below and made the changes accordingly.
https://github.com/microsoft/genalog/issues/61  --- (resolves the numpy error)
The next issue is the opencv-python package.
opencv-python==4.2.0.34

`INFO: pip is looking at multiple versions of genalog to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 3.4.11.39, 3.4.17.61, 4.4.0.42, 4.4.0.44, 4.5.4.58, 4.5.5.62, 4.7.0.68
ERROR: Ignored the following versions that require a different python version: 0.23.0 Requires-Python >=3.10; 0.23.0rc0 Requires-Python >=3.10; 0.23.0rc2 Requires-Python >=3.10; 0.23.1 Requires-Python >=3.10; 0.23.2 Requires-Python >=3.10; 0.23.2rc1 Requires-Python >=3.10; 0.25.0rc0 Requires-Python >=3.10; 0.25.0rc1 Requires-Python >=3.10; 2.1.0 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10; 2.1.1 Requires-Python >=3.10; 2.1.2 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.34 (from genalog) (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.60, 4.5.5.64, 4.6.0.66, 4.7.0.72, 4.8.0.74, 4.8.0.76, 4.8.1.78, 4.9.0.80, 4.10.0.82, 4.10.0.84)
ERROR: No matching distribution found for opencv-python==4.2.0.34`

The install is not successful with any other versions

**Comment by EmanuelaBoros** [comment]
This is what I have on my side now and it works opencv-python==4.10.0.84
I also update the requirements, could you try again?

**Comment by geeky-programer** [comment]
Can you also specify the version for the following packages? All these have conflicting requirements. 
requests
tqdm
scikit-image
pandas

**Comment by geeky-programer** [comment]
Yes this configuration is working. Thank you very much. The issue is with genalog install. Will need to raise an issue on their repo

**Comment by geeky-programer** [comment]
For reference genalog requirements.txt
`biopython==1.76
numpy==1.26.4
python-dotenv==0.11.0
requests==2.31.0
azure-core==1.10.0
azure-common==1.1.26
azure-storage-blob==12.3.1
tqdm==4.65.0
Jinja2==2.11.1
WeasyPrint==51
matplotlib==3.2.1
scikit-image==0.21.0
opencv-python==4.10.0.84
pandas==2.2.1
aiofiles==0.5.0
aiohttp==3.6.2`

**Comment by EmanuelaBoros** [comment]
Thank you! I updated the requirements. If it is all ok on your side, can I close the issue?

**Comment by geeky-programer** [comment]
Yes, close the issue
